
package ru.demo.client.generated_classes;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DiscriminantSolutionServiceDefaultImplService", targetNamespace = "http://soap_service.demo.ru/", wsdlLocation = "http://localhost:9083/ws/demo?wsdl")
public class DiscriminantSolutionServiceDefaultImplService
    extends Service
{

    private final static URL DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_EXCEPTION;
    private final static QName DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_QNAME = new QName("http://soap_service.demo.ru/", "DiscriminantSolutionServiceDefaultImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9083/ws/demo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_WSDL_LOCATION = url;
        DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_EXCEPTION = e;
    }

    public DiscriminantSolutionServiceDefaultImplService() {
        super(__getWsdlLocation(), DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_QNAME);
    }

    public DiscriminantSolutionServiceDefaultImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_QNAME, features);
    }

    public DiscriminantSolutionServiceDefaultImplService(URL wsdlLocation) {
        super(wsdlLocation, DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_QNAME);
    }

    public DiscriminantSolutionServiceDefaultImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_QNAME, features);
    }

    public DiscriminantSolutionServiceDefaultImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DiscriminantSolutionServiceDefaultImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DiscriminantSolutionService
     */
    @WebEndpoint(name = "DiscriminantSolutionServiceDefaultImplPort")
    public DiscriminantSolutionService getDiscriminantSolutionServiceDefaultImplPort() {
        return super.getPort(new QName("http://soap_service.demo.ru/", "DiscriminantSolutionServiceDefaultImplPort"), DiscriminantSolutionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DiscriminantSolutionService
     */
    @WebEndpoint(name = "DiscriminantSolutionServiceDefaultImplPort")
    public DiscriminantSolutionService getDiscriminantSolutionServiceDefaultImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap_service.demo.ru/", "DiscriminantSolutionServiceDefaultImplPort"), DiscriminantSolutionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_EXCEPTION!= null) {
            throw DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_EXCEPTION;
        }
        return DISCRIMINANTSOLUTIONSERVICEDEFAULTIMPLSERVICE_WSDL_LOCATION;
    }

}
