
package ru.demo.client.generated_classes;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "SolveNotFoundException", targetNamespace = "http://soap_service.demo.ru/")
public class SolveNotFoundException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SolveNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public SolveNotFoundException_Exception(String message, SolveNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public SolveNotFoundException_Exception(String message, SolveNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ru.demo.soap_service.SolveNotFoundException
     */
    public SolveNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
